
export const jobPostsTableField = [
  
  {title:'Submission', style:{width:'150px'}},
  {title:'Job Code',style:{width:'150px'}},
  {title:'Job Title',style:{width:'250px'}},
  // {title:'Business Unit'},
  {title:'Client',style:{width:'200px'}},
  {title:'Client Job ID',style:{width:'200px'}},

   // {title:'Client Job ID'},
  {title:'Location',style:{width:'200px'}},
  {title:'States',style:{width:'200px'}},
  {title:'Job Status',style:{width:'150px'}},
  {title:'Client Bill Rate/Salary',style:{width:'250px'}},
  // {title:'Pay Rate/Salary'},
  {title:'Delivery Manager',style:{width:'250px'}},
  {title:'Contact Manager',style:{width:'250px'}},
  {title:'Assigned To',style:{width:'300px'}},
  {title:'Job Created By',style:{width:'200px'}},
  {title:'Job Created',style:{width:'200px'}},
  {title:'Job Modified On',style:{width:'250px'}},
  // {title:'Min Salary'},
  // {title:'Max Salary'},
  // {title:'Average Salary'},
  {title:'Account Manager',style:{width:'200px'}},
  {title:'Action',style:{width:'150px'}},
  
]

export const clientData = [
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 67,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 68,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 69,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 70,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 71,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 72,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 73,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 74,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },

    {
      "select":'input',
      "client_id": 75,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 76,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 77,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
  ]