
export const jobPostsTableField = [
  
  {title:'input'},
  {title:'Job Code'},
  {title:'Job Title'},
  // {title:'Business Unit'},
  {title:'Client'},
  // {title:'Client Job ID'},
  {title:'Location'},
  {title:'States'},
  {title:'Job Status'},
  {title:'Client Bill Rate/Salary'},
  // {title:'Pay Rate/Salary'},
  {title:'Delivery Manager'},
  {title:'Contact Manager'},
  {title:'Assigned To'},
  {title:'Job Created By'},
  {title:'Job Created'},
  {title:'Job Modified On'},
  // {title:'Min Salary'},
  // {title:'Max Salary'},
  // {title:'Average Salary'},
  {title:'Account Manager'},
  {title:'Action'},
  
]

export const clientData = [
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 67,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 68,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 69,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 70,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 71,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 72,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 73,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 74,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },

    {
      "select":'input',
      "client_id": 75,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 76,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 77,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
  ]