export const userData = [
    {
      "id": 1,
      "empcode": 1011,
      "name": "Moriah.Stanton",
      "user_email": "moriah.stanton@demo.com",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "Recruiter",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
   {
      "id": 2,
      "empcode": 1012,
      "name": "Clementina DuBuque",
      "user_email": "anand.pandey@demo.com",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "Account Manager",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
    {
      "id": 3,
      "empcode": 1013,
      "name": "Aman Gour",
      "user_email": "moriah.stanton@demo.com",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "Deleievery Manager",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
    {
      "id": 4,
      "empcode": 1014,
      "name": "Shashikant",
      "user_email": "Moriah.Stanton",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "Recruiter",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
    {
      "id": 5,
      "empcode": 1015,
      "name": "Dharmendra Patel",
      "user_email": "moriah.stanton@deo.com",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "Recruiter",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
    {
      "id": 6,
      "empcode": 1016,
      "name": "Girish Soni",
      "user_email": "Moriah.Stanton",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "Recruiter",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
    {
      "id": 7,
      "empcode": 1017,
      "name": "Karthick Murthy",
      "user_email": "veryeasy@demo.com",
      "user_skype_id": "Moriah.Stanton",
      "user_role": "CTO",
      "user_team": "024-648-3804",
      "user_branch": "ambrose.net",
      "user_dept": "ambrose.net",
      "user_reportingmanager": "ambrose.net"
    },
    // {
    //   "id": 8,
    //   "empcode": 1018,
    //   "name": "Kshitij Kukreja",
    //   "user_email": "Moriah.Stanton",
    //   "user_skype_id": "Moriah.Stanton",
    //   "user_role": "CEO",
    //   "user_team": "024-648-3804",
    //   "user_branch": "ambrose.net",
    //   "user_dept": "ambrose.net",
    //   "user_reportingmanager": "ambrose.net"
    // },
    // {
    //   "id": 9,
    //   "empcode": 1019,
    //   "name": "Esha Kukreja",
    //   "user_email": "Moriah.Stanton",
    //   "user_skype_id": "Moriah.Stanton",
    //   "user_role": "",
    //   "user_team": "024-648-3804",
    //   "user_branch": "ambrose.net",
    //   "user_dept": "ambrose.net",
    //   "user_reportingmanager": "ambrose.net"
    // },
    // {
    //   "id": 10,
    //   "empcode": 1020,
    //   "name": "Vinay Wagh",
    //   "user_email": "Moriah.Stanton",
    //   "user_skype_id": "Moriah.Stanton",
    //   "user_role": "Admin",
    //   "user_team": "024-648-3804",
    //   "user_branch": "ambrose.net",
    //   "user_dept": "ambrose.net",
    //   "user_reportingmanager": "ambrose.net"
    // },
  ]