
export const clientTableField = [
  {title:"Client Contact", size:'130px'},
  {title:'Client Id', size:'150px'},
  {title:'Client Name', size:'250px'},
  {title:'Email', size:'300px'},
  {title:'Contact Number', size:'300px'},
  {title:'Website', size:'300px'},
  // {title:'Industry'},
  {title:'Status', size:'150px'},
  // {title:'Category'},
  {title:'Primary Owner', size:'200px'},
  // {title:'Business Unit'},
  // {title:'Display on Job Posting'},
  // {title:'Created by'},
  {title:'Created On', size:'250px'},
  {title:'Modified On', size:'250px'},
  {title:'Action', size:'260px'},
]

export const clientData = [
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
  ]