
export const clientTableField = [
  {title:"input"},
  {title:'Client Id'},
  {title:'Client Name'},
  {title:'Email'},
  {title:'Contact Number'},
  {title:'Website'},
  // {title:'Industry'},
  {title:'Status'},
  // {title:'Category'},
  {title:'Primary Owner'},
  // {title:'Business Unit'},
  // {title:'Display on Job Posting'},
  // {title:'Created by'},
  {title:'Created On'},
  {title:'Modified On'},
  {title:'Action'},
]

export const clientData = [
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      // "industry": "",
      "status": "Active",
      // "category": "",
      "primary_owner": "dharmendra patel",
      // "business_unit": "ktek",
      // "job_posting": "ambrose.net",
      // 'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
  ]