
export const clientTableField = [
  {title:"input"},
  {title:'Client Id'},
  {title:'Client Name'},
  {title:'Contact Number'},
  {title:'Website'},
  {title:'Industry'},
  {title:'Status'},
  {title:'Category'},
  {title:'Primary Owner'},
  {title:'Business Unit'},
  {title:'Display on Job Posting'},
  {title:'Created by'},
  {title:'Created On'},
  {title:'Modified On'},
  {title:'Action'},
]

export const clientData = [
    {
      "select":'input',
      "client_id": 66,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 67,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 68,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 69,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
    {
      "select":'input',
      "client_id": 70,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 71,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 72,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 73,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 74,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },

    {
      "select":'input',
      "client_id": 75,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 76,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
    {
      "select":'input',
      "client_id": 77,
      "client_name": 'Pepsico',
      "Contact_number": "",
      "website": "https://www.pepsico.com",
      "industry": "",
      "status": "Active",
      "category": "",
      "primary_owner": "dharmendra patel",
      "business_unit": "ktek",
      "job_posting": "ambrose.net",
      'created_by':'Dharmendra patel',
      'created_on':'06/11/2024 04:30 pm',
      'modified_on':'06/11/2024 04:30 pm',
    },
 
  ]